### ISSUE TITLE
[Solved] Don't work on Ubuntu 12.10 with LXC 0.8.0~rc1-4ubuntu39

### ISSUE THREAD

**Issue by ElieDeloumeau** [LennartC/LXC-Monitor#1]
Generate_charts.py won't work for me :(

Traceback (most recent call last):
  File "generate_charts.py", line 190, in <module>
    main()
  File "generate_charts.py", line 179, in main
    generateCPUChart(c, group, starttime, endtime, args.folder)
  File "generate_charts.py", line 91, in generateCPUChart
    g('set xtics %d ' % ( (diff[-1][0]-diff[0][0])/8,  ))
IndexError: list index out of range

**Comment by mkobel** [comment]
Do you have data in the database?

I had to change the paths in data_poller.py to the following ones:
- /sys/fs/cgroup/lxc/%s/memory.stat
- /sys/fs/cgroup/lxc/%s/cpuacct.usage

With these paths, it works on my Ubuntu 12.04 LTS

**Comment by ElieDeloumeau** [comment]
Yes i have all datas in the database. 

For me, it's :
- /sys/fs/cgroup/memory/lxc/%s/memory.stat
- /sys/fs/cgroup/cpuacct/lxc/%s/cpuacct.usage

I'm on ubuntu 12.10 (no errors when i run data_poller)

**Comment by ElieDeloumeau** [comment]
Oh, sorry...
i just forgot to put the full path : def_sqlitedb = "/root/LXC-Monitor/lxc_monitor.db"
